repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [ python ]
        args: [ --config=pyproject.toml ]
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [ python ]
        files: "\\.(py)$"
        args: [ --settings-path=pyproject.toml ]
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [ python ]
        args: [ --config-file=pyproject.toml ]
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [ python ]
        args: [ --rcfile=pyproject.toml ]
      - id: unittests
        name: unittests
        entry: python -m unittest
        language: system
        types: [ python ]
        pass_filenames: false